FROM nvidia/cuda:9.1-devel-ubuntu16.04
LABEL maintainer "danma <danma@yunify.com>"

RUN echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list

ENV CUDNN_VERSION 7.1.3.16
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

# Pick up some TF dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    apt-utils \
    rsync \
    zlib1g-dev \
    libhdf5-serial-dev \
    libpng12-0 \
    libpng12-dev \
    libzmq3-dev \
    libfreetype6 \
    libfreetype6-dev \
    pkg-config \
    python \
    python-dev \
    unzip \
    libcudnn7=$CUDNN_VERSION-1+cuda9.1 \
    libcudnn7-dev=$CUDNN_VERSION-1+cuda9.1 \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

#RUN mkdir /root/.pip
#COPY pip.conf /root/.pip

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

RUN pip --no-cache-dir install \
    Pillow \
    h5py \
    ipython==5.7.0 \
    ipykernel \
    jupyter \
    matplotlib \
    numpy==1.14.5 \
    pandas \
    scipy \
    sklearn \
    torch==1.0.1.post2 \
    torchvision==0.2.2.post3 \
    && \
    python -m ipykernel.kernelspec

#===================================================================================
RUN jupyter notebook --generate-config && \
    echo "c.NotebookApp.ip = '*'" >> /root/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.open_browser = False" >> /root/.jupyter/jupyter_notebook_config.py
RUN apt-get update && apt-get install -y --no-install-recommends dialog
#===================================================================================

ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH

EXPOSE 8888

WORKDIR "/root/"
