FROM nvidia/cuda:8.0-devel-ubuntu16.04
LABEL maintainer "carman <carmanzhang@yunify.com>"

RUN echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list

ENV CUDNN_VERSION 7.1.3.16
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

Run apt-get update && apt-get install -y --no-install-recommends \
        software-properties-common  && \
     apt-get clean

RUN add-apt-repository ppa:jonathonf/python-3.6 && \
        apt-get update && \
        apt-get install -y --no-install-recommends \
        build-essential \
        curl \
        apt-utils \
        python3.6 \
        python3.6-dev \
        rsync \
        zlib1g-dev \
        libhdf5-serial-dev \
        libpng12-0  \
        libpng12-dev \
        libzmq3-dev \
        libfreetype6  \
        libfreetype6-dev \
        pkg-config \
        unzip \
        vim \
        libcudnn7=$CUDNN_VERSION-1+cuda8.0 \
        libcudnn7-dev=$CUDNN_VERSION-1+cuda8.0 \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# remove python3.5 and link python3.6->python3
RUN apt-get -y purge --auto-remove python3.5 && \
        cd /usr/bin && \
        ln -s python3.6  python3  && \
        ln -s python3.6-config python3-config  && \
        ln -s python3.6m python3m  && \
        ln -s python3.6m-config python3m-config  && \
        ln -s x86_64-linux-gnu-python3.6-config x86_64-linux-gnu-python3-config  && \
        ln -s x86_64-linux-gnu-python3.6m-config x86_64-linux-gnu-python3m-config

#RUN mkdir /root/.pip
#COPY pip.conf /root/.pip

# pip for for python2.7 or pip3 for python3.6
RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    # if install pip for python3.6, only need to change python -> python3.6
    python3.6 get-pip.py && \
    rm get-pip.py

RUN pip3 --no-cache-dir install \
        Pillow \
        h5py \
        ipykernel \
        jupyter \
        matplotlib \
        numpy==1.14.5  \
        pandas \
        scipy \
        sklearn \
        torch \
        torchvision \
        && \
    python3.6 -m ipykernel.kernelspec

#===================================================================================
RUN jupyter notebook --generate-config && \
        echo "c.NotebookApp.ip = '*'" >> /root/.jupyter/jupyter_notebook_config.py && \
        echo "c.NotebookApp.open_browser = False" >> /root/.jupyter/jupyter_notebook_config.py
RUN apt-get update && apt-get install -y --no-install-recommends  dialog
#===================================================================================

ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH

EXPOSE 8888

WORKDIR "/root/"
