FROM nvidia/cuda:10.0-devel-ubuntu16.04
LABEL maintainer "danma <danma@yunify.com>"

RUN echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list

ENV CUDNN_VERSION 7.6.2.24
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

# Pick up some dependencies and python 2.7
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    software-properties-common \
    curl \
    apt-utils \
    python \
    python-dev \
    libcudnn7=$CUDNN_VERSION-1+cuda10.0 \
    libcudnn7-dev=$CUDNN_VERSION-1+cuda10.0 \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

RUN python -m pip --no-cache-dir install \
    Pillow \
    h5py \
    ipykernel \
    jupyter \
    matplotlib \
    numpy \
    pandas \
    scipy \
    sklearn \
    ipython \
    Cython \
    && \
    python -m ipykernel.kernelspec

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python3.5 get-pip.py && \
    rm get-pip.py && \
    cp /usr/local/bin/pip2 /usr/local/bin/pip

RUN pip3 --no-cache-dir install \
    Pillow \
    h5py \
    ipykernel \
    jupyter \
    matplotlib \
    numpy \
    pandas \
    scipy \
    sklearn \
    ipython \
    Cython \
    && \
    python3.5 -m ipykernel.kernelspec

# Config Jupyter Notebook
RUN ipython kernel install --name python3 && \
    jupyter notebook --generate-config && \
    echo "c.NotebookApp.ip = '*'" >> /root/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.open_browser = False" >> /root/.jupyter/jupyter_notebook_config.py
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends dialog

# Install TensorFlow GPU version.
RUN pip3 --no-cache-dir install https://appcenter-deeplearning.sh1a.qingstor.com/tensorflow/2.0.0/gpu/tensorflow_gpu-2.0.0-cp35-cp35m-manylinux2010_x86_64.whl && \
    pip --no-cache-dir install https://appcenter-deeplearning.sh1a.qingstor.com/tensorflow/2.0.0/gpu/tensorflow_gpu-2.0.0-cp27-cp27mu-manylinux2010_x86_64.whl

ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH

EXPOSE 6006
EXPOSE 8888

WORKDIR "/root/"
